"""Tests for context propagation with OTel spans."""

import pytest

from src.observability import (
    ObservabilityConfig,
    initialize_observability,
    shutdown,
)
from src.observability.context import (
    ObservabilityContext,
    ObservabilitySpan,
    _observability_context,
    get_or_create_context,
    reset_context,
    set_context,
)
from src.observability.handlers import NullHandler


@pytest.fixture(autouse=True)
def setup_observability():
    """Setup observability for each test.

    Initializes tracer and handler with console disabled.
    """
    handler = NullHandler()
    config = ObservabilityConfig(
        console_enabled=False,
        otel_endpoint="localhost:4317",  # Won't actually connect with NullHandler
        otel_insecure=True,
    )
    initialize_observability(handler=handler, config=config)
    # Reset context between tests
    _observability_context.set(None)
    yield
    shutdown()


def is_valid_hex(s: str, length: int) -> bool:
    """Check if string is valid hex of expected length."""
    if len(s) != length:
        return False
    try:
        int(s, 16)
        return True
    except ValueError:
        return False


class TestObservabilityContext:
    """Tests for ObservabilityContext dataclass."""

    def test_create_root_business_metadata(self):
        """Test creating a root context has proper business metadata."""
        ctx = ObservabilityContext.create_root()

        # Business metadata should be generated
        assert ctx.session_id.startswith("sess_")
        assert ctx.request_id.startswith("req_")
        assert ctx.component_stack == ["root"]

    def test_create_root_no_span_returns_empty_ids(self):
        """Test that root context without OTel span has empty IDs."""
        ctx = ObservabilityContext.create_root()

        # Without an active OTel span, IDs are empty
        # (IDs come from OTel span, not generated by us)
        assert ctx.trace_id == "" or is_valid_hex(ctx.trace_id, 32)
        assert ctx.span_id == "" or is_valid_hex(ctx.span_id, 16)
        assert ctx.parent_span_id is None

    def test_create_root_with_session_id(self):
        """Test creating root context with custom session ID."""
        ctx = ObservabilityContext.create_root(session_id="custom_session")

        assert ctx.session_id == "custom_session"

    def test_create_child_inherits_business_metadata(self):
        """Test that child inherits session and request from parent."""
        parent = ObservabilityContext.create_root()
        child = parent.create_child("my_component")

        # Child inherits business metadata
        assert child.session_id == parent.session_id
        assert child.request_id == parent.request_id

        # Component stack is extended
        assert child.component_stack == ["root", "my_component"]

    def test_triggered_by(self):
        """Test triggered_by property."""
        root = ObservabilityContext.create_root()
        assert root.triggered_by == "direct_call"

        child1 = root.create_child("component1")
        assert child1.triggered_by == "root"

        child2 = child1.create_child("component2")
        assert child2.triggered_by == "component1"

    def test_current_component(self):
        """Test current_component property."""
        root = ObservabilityContext.create_root()
        assert root.current_component == "root"

        child = root.create_child("my_tool")
        assert child.current_component == "my_tool"

    def test_to_dict(self):
        """Test serialization to dictionary."""
        ctx = ObservabilityContext.create_root()
        data = ctx.to_dict()

        assert "trace_id" in data
        assert "span_id" in data
        assert "parent_span_id" in data
        assert "session_id" in data
        assert "request_id" in data
        assert "triggered_by" in data
        assert "component_stack" in data
        assert "start_time" in data


class TestContextFunctions:
    """Tests for context management functions."""

    def test_get_or_create_creates_root(self):
        """Test that get_or_create_context creates a root if none exists."""
        # Reset context first
        _observability_context.set(None)

        ctx = get_or_create_context("test_component")

        assert ctx is not None
        # Business metadata should be set
        assert ctx.session_id.startswith("sess_")
        assert ctx.component_stack == ["test_component"]

    def test_set_and_reset_context(self):
        """Test setting and resetting context."""
        original = ObservabilityContext.create_root()
        token = set_context(original)

        current = ObservabilityContext.get_current()
        assert current == original

        reset_context(token)


class TestObservabilitySpan:
    """Tests for ObservabilitySpan context manager with OTel spans."""

    def test_span_creates_valid_otel_ids(self):
        """Test that span creates valid OTel trace/span IDs."""
        _observability_context.set(None)

        with ObservabilitySpan("test_span") as ctx:
            # With an OTel span active, we should have valid IDs
            assert is_valid_hex(ctx.trace_id, 32), (
                f"trace_id should be 32 hex chars, got: {ctx.trace_id}"
            )
            assert is_valid_hex(ctx.span_id, 16), (
                f"span_id should be 16 hex chars, got: {ctx.span_id}"
            )
            assert "test_span" in ctx.component_stack

    def test_span_inherits_business_metadata(self):
        """Test that span inherits session_id from parent context."""
        parent = ObservabilityContext.create_root(session_id="my_session")
        set_context(parent)

        with ObservabilitySpan("test_span") as ctx:
            assert ctx.session_id == "my_session"

    def test_span_restores_context(self):
        """Test that span restores original context on exit."""
        parent = ObservabilityContext.create_root()
        token = set_context(parent)

        parent_session = parent.session_id

        with ObservabilitySpan("test_span"):
            pass

        # After exiting, context should be restored
        current = ObservabilityContext.get_current()
        assert current.session_id == parent_session

        reset_context(token)

    def test_nested_spans_share_trace_id(self):
        """Test nested span context managers share trace_id."""
        _observability_context.set(None)

        with ObservabilitySpan("level1") as ctx1:
            trace_id_1 = ctx1.trace_id
            span_id_1 = ctx1.span_id

            with ObservabilitySpan("level2") as ctx2:
                trace_id_2 = ctx2.trace_id
                span_id_2 = ctx2.span_id
                parent_span_id_2 = ctx2.parent_span_id

                # Both have valid IDs
                assert is_valid_hex(trace_id_1, 32)
                assert is_valid_hex(trace_id_2, 32)
                assert is_valid_hex(span_id_1, 16)
                assert is_valid_hex(span_id_2, 16)

                # Same trace_id (inherited)
                assert trace_id_1 == trace_id_2

                # Different span_ids
                assert span_id_1 != span_id_2

                # Inner's parent is outer's span
                assert parent_span_id_2 == span_id_1

    def test_nested_spans_triggered_by(self):
        """Test triggered_by chain in nested spans."""
        _observability_context.set(None)

        with ObservabilitySpan("level1") as ctx1:
            assert ctx1.triggered_by == "direct_call" or ctx1.triggered_by == "unknown"

            with ObservabilitySpan("level2") as ctx2:
                assert ctx2.triggered_by == "level1"

                with ObservabilitySpan("level3") as ctx3:
                    assert ctx3.triggered_by == "level2"


class TestOTelSpanFormats:
    """Tests for OTel ID format compliance."""

    def test_trace_id_format(self):
        """Test that trace_id is 32-char hex (128-bit)."""
        with ObservabilitySpan("test") as ctx:
            trace_id = ctx.trace_id
            assert len(trace_id) == 32, f"Expected 32 chars, got {len(trace_id)}"
            # Should be valid hex
            int(trace_id, 16)

    def test_span_id_format(self):
        """Test that span_id is 16-char hex (64-bit)."""
        with ObservabilitySpan("test") as ctx:
            span_id = ctx.span_id
            assert len(span_id) == 16, f"Expected 16 chars, got {len(span_id)}"
            # Should be valid hex
            int(span_id, 16)

    def test_parent_span_id_format(self):
        """Test that parent_span_id is 16-char hex when present."""
        with ObservabilitySpan("parent") as parent_ctx:
            parent_span = parent_ctx.span_id

            with ObservabilitySpan("child") as child_ctx:
                parent_span_id = child_ctx.parent_span_id

                assert parent_span_id is not None
                assert len(parent_span_id) == 16, f"Expected 16 chars, got {len(parent_span_id)}"
                # Should be valid hex
                int(parent_span_id, 16)
                # Should match parent's span_id
                assert parent_span_id == parent_span
