"""OpenTelemetry tracer provider setup.

Single source of truth for trace/span creation.
All IDs are generated by OTel - no custom generation.

Usage:
    from src.observability.tracer import init_tracer, get_tracer

    # At application startup
    init_tracer(endpoint="localhost:4317", service_name="my-service")

    # In decorators/code
    tracer = get_tracer()
    with tracer.start_as_current_span("my_operation") as span:
        ...
"""

from typing import Optional
from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.sdk.resources import Resource, SERVICE_NAME


# Global tracer instance
_tracer: Optional[trace.Tracer] = None
_provider: Optional[TracerProvider] = None


def init_tracer(
    endpoint: str = "localhost:4317",
    service_name: str = "crawler-agent",
    insecure: bool = True
) -> trace.Tracer:
    """Initialize the global OTel tracer.

    Must be called once at application startup before any tracing.

    Args:
        endpoint: OTel Collector endpoint (host:port)
        service_name: Service name for traces
        insecure: Whether to use insecure connection

    Returns:
        Configured Tracer instance
    """
    global _tracer, _provider

    try:
        from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter

        resource = Resource.create({SERVICE_NAME: service_name})
        _provider = TracerProvider(resource=resource)

        exporter = OTLPSpanExporter(
            endpoint=endpoint,
            insecure=insecure
        )
        _provider.add_span_processor(BatchSpanProcessor(exporter))

        trace.set_tracer_provider(_provider)
        _tracer = trace.get_tracer(service_name)

        return _tracer

    except ImportError as e:
        print(f"Warning: OTel trace packages not installed: {e}")
        # Return no-op tracer
        _tracer = trace.get_tracer(service_name)
        return _tracer
    except Exception as e:
        print(f"Warning: Failed to initialize OTel tracer: {e}")
        _tracer = trace.get_tracer(service_name)
        return _tracer


def get_tracer() -> trace.Tracer:
    """Get the global tracer instance.

    Returns no-op tracer if not initialized.

    Returns:
        Tracer instance
    """
    global _tracer
    if _tracer is None:
        # Return no-op tracer if not initialized
        _tracer = trace.get_tracer("uninitialized")
    return _tracer


def get_current_span() -> trace.Span:
    """Get the current active span.

    Returns:
        Current span or NonRecordingSpan if none active
    """
    return trace.get_current_span()


def shutdown_tracer() -> None:
    """Shutdown the tracer provider and flush pending spans."""
    global _provider
    if _provider is not None:
        try:
            _provider.force_flush()
            _provider.shutdown()
        except Exception:
            pass


def format_trace_id(trace_id: int) -> str:
    """Format OTel trace ID (128-bit int) as 32-char hex string.

    Args:
        trace_id: 128-bit integer trace ID from OTel

    Returns:
        32-character hex string
    """
    return format(trace_id, '032x')


def format_span_id(span_id: int) -> str:
    """Format OTel span ID (64-bit int) as 16-char hex string.

    Args:
        span_id: 64-bit integer span ID from OTel

    Returns:
        16-character hex string
    """
    return format(span_id, '016x')
